### ISSUE TITLE
Could this be pushed to CTAN ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jrnold/lstbayes#1]
Dear Jeffrey,

Thank you for this addition to Stan and listings : this is _really_ useful to Stan users who try to publish their work cleanly.
However, this packages is almost unfindable : I found it by accident by lurking on the stan-dev mailing list (Google group).
Could it be pushed either to the original `listings.sty` authors and/or CTAN ? This latter being even more important, since it would percolate to the major TeX distributions (TeXLive, MikTeX, etc...), thus making your package discoverable and useable.
Sincerely yours,

**Comment by jrnold** [comment]
It seemed a little trival to be on CTAN, so I was reluctant to go through the trouble. I emailed the new maintainer of `listings.sty` a little while  ago to get it included (my first best option), but I haven't heard back. I'll think about it. I should probably start by renaming it from BUGS to something else.

**Comment by jrnold** [comment]
Just wanted to update you on this. I refactored the code into a proper LaTeX package with `.dtx`, `.ins` and all that. I pushed it to CTAN today, and I also sent an email to the current listings maintainer to see if the languages could get into the listings package.

**Comment by jrnold** [comment]
Now on CTAN! https://www.ctan.org/search/?phrase=lstbayes
